ignore-bounds-checks: true

# ns-per-frame: 100000000 # 10 fps
# ns-per-frame: 66666666 # 15 fps
ns-per-frame: 50000000 # 20 fps
# ns-per-frame: 40000000 # 25 fps
# ns-per-frame: 33333333 # 30 fps
# ns-per-frame: 25000000 # 40 fps

matrix-specs:
  "ws2812b:32x16":
    power_limit_amps: 2.5
    width-height: [16, 32]

  "ws2812b:64x64":
    power_limit_amps: 2.5
    width-height: [64, 64]

matrices:

  # Row 1

  mat1:
    spec: "ws2812b:32x16"
    pos: [0, 0]
    rot: down
  mat2:
    spec: "ws2812b:32x16"
    pos: [16, 0]
    rot: down
  mat3:
    spec: "ws2812b:32x16"
    pos: [32, 0]
    rot: down
  mat4:
    spec: "ws2812b:32x16"
    pos: [48, 0]
    rot: down

  # Row 2

  mat5:
    spec: "ws2812b:32x16"
    pos: [0, 32]
    rot: down
  mat6:
    spec: "ws2812b:32x16"
    pos: [16, 32]
    rot: down
  mat7:
    spec: "ws2812b:32x16"
    pos: [32, 32]
    rot: down
  mat8:
    spec: "ws2812b:32x16"
    pos: [48, 32]
    rot: down

  # Row 3

  mat9:
    spec: "ws2812b:32x16"
    pos: [0, 64]
    rot: down
  mat10:
    spec: "ws2812b:32x16"
    pos: [16, 64]
    rot: down
  mat11:
    spec: "ws2812b:32x16"
    pos: [32, 64]
    rot: down
  mat12:
    spec: "ws2812b:32x16"
    pos: [48, 64]
    rot: down

  # Row 4

  mat13:
    spec: "ws2812b:32x16"
    pos: [0, 96]
    rot: down
  mat14:
    spec: "ws2812b:32x16"
    pos: [16, 96]
    rot: down
  mat15:
    spec: "ws2812b:32x16"
    pos: [32, 96]
    rot: down
  mat16:
    spec: "ws2812b:32x16"
    pos: [48, 96]
    rot: down

  # Right

  mat17:
    spec: "ws2812b:64x64"
    pos: [64, 0]
    rot: down
  mat18:
    spec: "ws2812b:64x64"
    pos: [64, 64]
    rot: down

clients:
  AA-AA-AA-AA-AA-AA:
    matrix-connections:
      - pin: 16
        matrices: [mat1]
      - pin: 17
        matrices: [mat2]
      - pin: 18
        matrices: [mat3]
      - pin: 19
        matrices: [mat4]
  BB-BB-BB-BB-BB-BB:
    matrix-connections:
      - pin: 16
        matrices: [mat5]
      - pin: 17
        matrices: [mat6]
      - pin: 18
        matrices: [mat7]
      - pin: 19
        matrices: [mat8]
  CC-CC-CC-CC-CC-CC:
    matrix-connections:
      - pin: 16
        matrices: [mat9]
      - pin: 17
        matrices: [mat10]
      - pin: 18
        matrices: [mat11]
      - pin: 19
        matrices: [mat12]
  DD-DD-DD-DD-DD-DD:
    matrix-connections:
      - pin: 16
        matrices: [mat13]
      - pin: 17
        matrices: [mat14]
      - pin: 18
        matrices: [mat15]
      - pin: 19
        matrices: [mat16]
  EE-EE-EE-EE-EE-EE:
    matrix-connections:
      - pin: 16
        matrices: [mat17]
      - pin: 17
        matrices: [mat18]

