ignore-bounds-checks: true

# ns-per-frame: 100000000 # 10 fps
# ns-per-frame: 66666666 # 15 fps
ns-per-frame: 50000000 # 20 fps
# ns-per-frame: 40000000 # 25 fps
# ns-per-frame: 33333333 # 30 fps
# ns-per-frame: 25000000 # 40 fps

matrix-specs:
  "ws2812b:32x8":
    power_limit_amps: 2.5
    width-height: [8, 32]

matrices:

  # Row 1

  mat1:
    spec: "ws2812b:32x8"
    pos: [0, 0]
    rot: down
  mat2:
    spec: "ws2812b:32x8"
    pos: [8, 0]
    rot: down
  mat3:
    spec: "ws2812b:32x8"
    pos: [16, 0]
    rot: down
  mat4:
    spec: "ws2812b:32x8"
    pos: [24, 0]
    rot: down
  mat5:
    spec: "ws2812b:32x8"
    pos: [32, 0]
    rot: down
  mat6:
    spec: "ws2812b:32x8"
    pos: [40, 0]
    rot: down
  mat7:
    spec: "ws2812b:32x8"
    pos: [48, 0]
    rot: down
  mat8:
    spec: "ws2812b:32x8"
    pos: [56, 0]
    rot: down

  # Row 2

  mat9:
    spec: "ws2812b:32x8"
    pos: [0, 32]
    rot: down
  mat10:
    spec: "ws2812b:32x8"
    pos: [8, 32]
    rot: down
  mat11:
    spec: "ws2812b:32x8"
    pos: [16, 32]
    rot: down
  mat12:
    spec: "ws2812b:32x8"
    pos: [24, 32]
    rot: down
  mat13:
    spec: "ws2812b:32x8"
    pos: [32, 32]
    rot: down
  mat14:
    spec: "ws2812b:32x8"
    pos: [40, 32]
    rot: down
  mat15:
    spec: "ws2812b:32x8"
    pos: [48, 32]
    rot: down
  mat16:
    spec: "ws2812b:32x8"
    pos: [56, 32]
    rot: down

  # Row 3

  mat17:
    spec: "ws2812b:32x8"
    pos: [0, 64]
    rot: down
  mat18:
    spec: "ws2812b:32x8"
    pos: [8, 64]
    rot: down
  mat19:
    spec: "ws2812b:32x8"
    pos: [16, 64]
    rot: down
  mat20:
    spec: "ws2812b:32x8"
    pos: [24, 64]
    rot: down
  mat21:
    spec: "ws2812b:32x8"
    pos: [32, 64]
    rot: down
  mat22:
    spec: "ws2812b:32x8"
    pos: [40, 64]
    rot: down
  mat23:
    spec: "ws2812b:32x8"
    pos: [48, 64]
    rot: down
  mat24:
    spec: "ws2812b:32x8"
    pos: [56, 64]
    rot: down

  # Row 4

  mat25:
    spec: "ws2812b:32x8"
    pos: [0, 96]
    rot: down
  mat26:
    spec: "ws2812b:32x8"
    pos: [8, 96]
    rot: down
  mat27:
    spec: "ws2812b:32x8"
    pos: [16, 96]
    rot: down
  mat28:
    spec: "ws2812b:32x8"
    pos: [24, 96]
    rot: down
  mat29:
    spec: "ws2812b:32x8"
    pos: [32, 96]
    rot: down
  mat30:
    spec: "ws2812b:32x8"
    pos: [40, 96]
    rot: down
  mat31:
    spec: "ws2812b:32x8"
    pos: [48, 96]
    rot: down
  mat32:
    spec: "ws2812b:32x8"
    pos: [56, 96]
    rot: down

clients:
  AA-AA-AA-AA-AA-AA:
    matrix-connections:
      - pin: 16
        matrices: [mat1]
      - pin: 17
        matrices: [mat2]
      - pin: 18
        matrices: [mat3]
      - pin: 19
        matrices: [mat4]
  BB-BB-BB-BB-BB-BB:
    matrix-connections:
      - pin: 16
        matrices: [mat5]
      - pin: 17
        matrices: [mat6]
      - pin: 18
        matrices: [mat7]
      - pin: 19
        matrices: [mat8]
  CC-CC-CC-CC-CC-CC:
    matrix-connections:
      - pin: 16
        matrices: [mat9]
      - pin: 17
        matrices: [mat10]
      - pin: 18
        matrices: [mat11]
      - pin: 19
        matrices: [mat12]
  DD-DD-DD-DD-DD-DD:
    matrix-connections:
      - pin: 16
        matrices: [mat13]
      - pin: 17
        matrices: [mat14]
      - pin: 18
        matrices: [mat15]
      - pin: 19
        matrices: [mat16]
  EE-EE-EE-EE-EE-EE:
    matrix-connections:
      - pin: 16
        matrices: [mat17]
      - pin: 17
        matrices: [mat18]
      - pin: 18
        matrices: [mat19]
      - pin: 19
        matrices: [mat20]
  FF-FF-FF-FF-FF-FF:
    matrix-connections:
      - pin: 16
        matrices: [mat21]
      - pin: 17
        matrices: [mat22]
      - pin: 18
        matrices: [mat23]
      - pin: 19
        matrices: [mat24]
  00-00-00-00-00-00:
    matrix-connections:
      - pin: 16
        matrices: [mat25]
      - pin: 17
        matrices: [mat26]
      - pin: 18
        matrices: [mat27]
      - pin: 19
        matrices: [mat28]
  11-11-11-11-11-11:
    matrix-connections:
      - pin: 16
        matrices: [mat29]
      - pin: 17
        matrices: [mat30]
      - pin: 18
        matrices: [mat31]
      - pin: 19
        matrices: [mat32]
